version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      target-branch: dev
      schedule:
          interval: "weekly"
      ignore:
          # https://github.com/st-user/zerodep-web-push-java/issues/52
          - dependency-name: "org.eclipse.jetty:jetty-client"
          # https://github.com/st-user/zerodep-web-push-java/issues/108
          - dependency-name: "com.nimbusds:nimbus-jose-jwt"
          # https://github.com/st-user/zerodep-web-push-java/issues/109
          - dependency-name: "com.squareup.okhttp3:okhttp"
          # https://github.com/st-user/zerodep-web-push-java/issues/111
          - dependency-name: "org.junit.jupiter:junit-jupiter-api"
          - dependency-name: "org.junit.jupiter:junit-jupiter-engine"
          # https://github.com/st-user/zerodep-web-push-java/issues/112
          - dependency-name: "com.fasterxml.jackson.core:jackson-core"
          - dependency-name: "com.fasterxml.jackson.core:jackson-annotations"
          - dependency-name: "com.fasterxml.jackson.core:jackson-databind"

    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: dev
      schedule:
          interval: "weekly"
